runtime: nodejs18
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  DB_USER: melodyoasis123
  DB_PASS: melodyoasis2246
  DB_NAME: melodyoasis
  INSTANCE_CONNECTION_NAME: nodal-buckeye-404908:asia-east1:melodyoasis123